spring.application.name=energiaai
# Puerto de tu servidor Backend
server.port=8080

# -----------------------------------------------------
# CONEXIÓN A POSTGRESQL
# -----------------------------------------------------
# Asegúrate de haber creado la base de datos 'energia_db' en pgAdmin o consola
spring.datasource.url=jdbc:postgresql://localhost:5432/energia_db

# El usuario por defecto en Postgres suele ser 'postgres'
spring.datasource.username=postgres
spring.datasource.password=tu_contraseña_aqui

# -----------------------------------------------------
# CONFIGURACIÓN DE HIBERNATE (JPA)
# -----------------------------------------------------
# El dialecto le enseña a Spring cómo hablar en "idioma Postgres"
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Crea o actualiza las tablas automáticamente basándose en tus @Entity
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas en la consola (útil para ver qué hace por detrás)
spring.jpa.show-sql=true