-- Migración Flyway V2: Creación de tablas de Análisis Energético (Request y Response)

CREATE TABLE IF NOT EXISTS analisis_energetico_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    identificador VARCHAR(255) NOT NULL,
    region VARCHAR(255),
    consumo_kwh DOUBLE PRECISION,
    uso_horario_pico BOOLEAN,
    cantidad_equipos INT,
    tipo_inmueble VARCHAR(255),
    horas_alto_consumo INT,
    fecha_creacion TIMESTAMP,
    CONSTRAINT fk_request_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS analisis_energetico_response (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    categoria VARCHAR(255),
    probabilidad DOUBLE PRECISION,
    costo_estimado_mensual DOUBLE PRECISION,
    recomendaciones VARCHAR(2000),
    fecha_creacion TIMESTAMP,
    CONSTRAINT fk_response_request FOREIGN KEY (request_id) REFERENCES analisis_energetico_request(id) ON DELETE CASCADE
);