CREATE TABLE IF NOT EXISTS analisis_energetico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    identificador VARCHAR(255),
    categoria VARCHAR(255),
    probabilidad DOUBLE PRECISION,
    costo_estimado_mensual DOUBLE PRECISION,
    fecha_creacion TIMESTAMP,
    region VARCHAR(255),
    consumo_kwh DOUBLE PRECISION,
    uso_horario_pico BOOLEAN,
    cantidad_equipos INT,
    tipo_inmueble VARCHAR(255),
    horas_alto_consumo INT,
    CONSTRAINT fk_analisis_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS analisis_recomendaciones (
    analisis_id BIGINT NOT NULL,
    recomendaciones VARCHAR(500),
    CONSTRAINT fk_analisis_recomendaciones FOREIGN KEY (analisis_id) REFERENCES analisis_energetico(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS analisis_energetico_response (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria VARCHAR(255),
    probabilidad DOUBLE PRECISION,
    costo_estimado_mensual DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS analisis_energetico_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region VARCHAR(255),
    consumo_kwh DOUBLE PRECISION,
    uso_horario_pico BOOLEAN,
    cantidad_equipos INT,
    tipo_inmueble VARCHAR(255),
    horas_alto_consumo INT,
    analisis_respuesta_id BIGINT,
    CONSTRAINT fk_analisis_respuesta FOREIGN KEY (analisis_respuesta_id) REFERENCES analisis_energetico_response(id)
);